name: Cache
description: Persist cache in between build steps
author: https://github.com/buildkite-plugins
requirements: []
configuration:
  properties:
    backend:
      type: string
    level:
      type: string
      enum:
        - file
        - step
        - branch
        - pipeline
        - all
    manifest:
      type: string
    restore:
      type: string
    save:
      type: string
  additionalProperties: false
  anyOf:
    - required:
      - restore
    - required:
      - save