name: Cache
description: Persist cache in between build steps
author: https://github.com/buildkite-plugins
requirements: []
configuration:
  properties:
    backend:
      type: string
    path:
      type: string
    manifest:
      type: string
    restore:
      type: string
      enum:
        - file
        - step
        - branch
        - pipeline
        - all
    save:
      type: string
      enum:
        - file
        - step
        - branch
        - pipeline
        - all
  additionalProperties: false
  required:
    - path
