steps:
  - label: ":shell: Tests"
    plugins:
      docker-compose#v2.5.1:
        run: tests

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files: hooks/**

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: cache
